### ISSUE TITLE
Roadmap and Ideas

### ISSUE THREAD

**Issue by tdittr** [tdittr/histongram#5]
## Roadmap
- [ ] Write a roadmap...

## Ideas
- Datastructures and Algorithms
    - [ ] Ngram Histogram that can count multiple n-grams with one pass
    - [ ] Comparison of different Histograms
        - Which ngram is typical for a specific distribution (e.g. "the" is usually note specific, while "borrowchecker" is)
    - [ ] Calculate information content (Inspired by 3b1b Wordle Solver video) 
- Testing
    - [ ] Add property based tests to compare this against nltk
- Documentation
    - [ ] Add Rust examples
    - [ ] Add Python examples
    - [ ] Add Sphinx documentation generation
- CI
    - [ ] Figure out how to publish on tag
    - [ ] Enable cross compilation for Linux
    - [ ] Install generated wheels and run `pytest`
